### ISSUE TITLE
Error when try to print report

### ISSUE THREAD

**Issue by tsobeng** [xcgd/account_bank_reconciliation#1]
Hi all,
I have this error when I try to print any report on Odoo8. Please help!
2015-07-20 14:07:10,951 12372 ERROR Local-20-06-15 openerp.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server\openerp\addons\web\controllers\main.py", line 69, in wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server\openerp\addons\web\controllers\main.py", line 1577, in index
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\http.py", line 872, in proxy_method
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\http.py", line 114, in dispatch_rpc
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\service\report.py", line 34, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\service\report.py", line 141, in exp_report_get
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\service\report.py", line 119, in _check_report
except_orm: (u"expected token ',', got 'string'", (<class 'jinja2.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("expected token ',', got 'string'",), <traceback object at 0x07171670>))

**Comment by yasminamina** [comment]
hellow,
 i need your helps , i have this error when I try to print any report : 
Encountered unknown tag 'page'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.

<class 'jinja2.exceptions.TemplateSyntaxError'>,Encountered unknown tag 'page'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.,<traceback object at 0x0340F508>
